# Generated by Django 2.0.1 on 2018-01-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adduser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('ename', models.CharField(max_length=20, verbose_name='英文姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], default=1, verbose_name='性别')),
                ('nation', models.CharField(max_length=20, verbose_name='国籍')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('passport', models.CharField(max_length=20, verbose_name='护照号码')),
                ('idcard', models.CharField(max_length=20, verbose_name='身份证号')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机号码')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信')),
                ('email', models.CharField(max_length=20, verbose_name='电子邮箱')),
                ('add', models.CharField(max_length=20, verbose_name='邮寄地址')),
                ('money', models.BigIntegerField(verbose_name='会费')),
                ('company', models.CharField(max_length=20, verbose_name='公司')),
                ('industry', models.CharField(max_length=20, verbose_name='公司行业')),
                ('firmsize', models.CharField(max_length=20, verbose_name='公司规模')),
                ('financingsituation', models.CharField(max_length=20, verbose_name='资产规模')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
                ('title', models.CharField(max_length=20, verbose_name='职位')),
                ('comadd', models.CharField(max_length=20, verbose_name='公司地址')),
                ('hobby', models.CharField(max_length=20, verbose_name='爱好')),
                ('recom1', models.CharField(max_length=20, verbose_name='推荐人1')),
                ('reason1', models.CharField(max_length=20, verbose_name='推荐理由')),
                ('recom2', models.CharField(max_length=20, verbose_name='推荐人2')),
                ('reason2', models.CharField(max_length=20, verbose_name='推荐理由2')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumename', models.CharField(max_length=40, verbose_name='消费名称')),
                ('add', models.CharField(max_length=20, verbose_name='消费地点')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='消费金额')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='消费人数')),
                ('consumetimes', models.DateTimeField(verbose_name='消费时间')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('name', models.ManyToManyField(to='main.adduser', verbose_name='消费用户')),
            ],
            options={
                'verbose_name': '消费名称',
                'verbose_name_plural': '消费名称',
                'ordering': ['consumename'],
            },
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardinality', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adduser', verbose_name='用户姓名')),
            ],
        ),
    ]
