# Generated by Django 2.0.1 on 2018-01-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_points_pointstimes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['id'], 'verbose_name': '积分充值', 'verbose_name_plural': '积分充值'},
        ),
    ]
