# Generated by Django 2.0.1 on 2018-01-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180114_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['name'], 'verbose_name': '积分充值', 'verbose_name_plural': '积分充值'},
        ),
    ]
